// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SporSalonu2.Data;

#nullable disable

namespace SporSalonu2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SporSalonu2.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsBookable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Availabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsBookable = true,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsBookable = true,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            TrainerId = 1
                        });
                });

            modelBuilder.Entity("SporSalonu2.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SporSalonu2.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kardiyo ve genel form.",
                            DurationMinutes = 60,
                            Name = "Fitness",
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Esneklik ve denge.",
                            DurationMinutes = 45,
                            Name = "Yoga",
                            Price = 400m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Core güçlendirme.",
                            DurationMinutes = 50,
                            Name = "Pilates",
                            Price = 450m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Serbest ağırlık ve vücut geliştirme.",
                            DurationMinutes = 90,
                            Name = "Gym & Ağırlık",
                            Price = 500m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Yüzme antrenmanları.",
                            DurationMinutes = 60,
                            Name = "Havuz",
                            Price = 600m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Boks ve kickboks dersleri.",
                            DurationMinutes = 60,
                            Name = "Boks",
                            Price = 550m
                        });
                });

            modelBuilder.Entity("SporSalonu2.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Kişisel antrenör ve beslenme danışmanı.",
                            Email = "ahmet@fitzone.com",
                            FirstName = "Ahmet",
                            LastName = "Yılmaz",
                            Phone = "5551112233",
                            Specialty = "Fitness & Kilo Verme"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Uzman yoga eğitmeni.",
                            Email = "zeynep@fitzone.com",
                            FirstName = "Zeynep",
                            LastName = "Kara",
                            Phone = "5554445566",
                            Specialty = "Yoga & Meditasyon"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Reformer ve mat pilates uzmanı.",
                            Email = "mehmet@fitzone.com",
                            FirstName = "Mehmet",
                            LastName = "Demir",
                            Phone = "5557778899",
                            Specialty = "Pilates & Rehabilitasyon"
                        });
                });

            modelBuilder.Entity("SporSalonu2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SporSalonu2.Models.Availability", b =>
                {
                    b.HasOne("SporSalonu2.Models.Trainer", "Trainer")
                        .WithMany("Availabilities")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("SporSalonu2.Models.Booking", b =>
                {
                    b.HasOne("SporSalonu2.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SporSalonu2.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("SporSalonu2.Models.Trainer", b =>
                {
                    b.Navigation("Availabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
